// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gapic/metadata/gapic_metadata.proto

package com.google.gapic.metadata;

public final class GapicMetadataProto {
  private GapicMetadataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_gapic_metadata_GapicMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_gapic_metadata_GapicMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_gapic_metadata_GapicMetadata_ServicesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_gapic_metadata_GapicMetadata_ServicesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_ClientsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_ClientsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_RpcsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_RpcsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_gapic_metadata_GapicMetadata_MethodList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_gapic_metadata_GapicMetadata_MethodList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#gapic/metadata/gapic_metadata.proto\022\025g" +
      "oogle.gapic.metadata\"\205\006\n\rGapicMetadata\022\016" +
      "\n\006schema\030\001 \001(\t\022\017\n\007comment\030\002 \001(\t\022\020\n\010langu" +
      "age\030\003 \001(\t\022\025\n\rproto_package\030\004 \001(\t\022\027\n\017libr" +
      "ary_package\030\005 \001(\t\022D\n\010services\030\006 \003(\01322.go" +
      "ogle.gapic.metadata.GapicMetadata.Servic" +
      "esEntry\032i\n\rServicesEntry\022\013\n\003key\030\001 \001(\t\022G\n" +
      "\005value\030\002 \001(\01328.google.gapic.metadata.Gap" +
      "icMetadata.ServiceForTransport:\0028\001\032\350\001\n\023S" +
      "erviceForTransport\022V\n\007clients\030\001 \003(\0132E.go" +
      "ogle.gapic.metadata.GapicMetadata.Servic" +
      "eForTransport.ClientsEntry\022\023\n\013api_versio" +
      "n\030\002 \001(\t\032d\n\014ClientsEntry\022\013\n\003key\030\001 \001(\t\022C\n\005" +
      "value\030\002 \001(\01324.google.gapic.metadata.Gapi" +
      "cMetadata.ServiceAsClient:\0028\001\032\325\001\n\017Servic" +
      "eAsClient\022\026\n\016library_client\030\001 \001(\t\022L\n\004rpc" +
      "s\030\002 \003(\0132>.google.gapic.metadata.GapicMet" +
      "adata.ServiceAsClient.RpcsEntry\032\\\n\tRpcsE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022>\n\005value\030\002 \001(\0132/.googl" +
      "e.gapic.metadata.GapicMetadata.MethodLis" +
      "t:\0028\001\032\035\n\nMethodList\022\017\n\007methods\030\001 \003(\tB\272\001\n" +
      "\031com.google.gapic.metadataB\022GapicMetadat" +
      "aProtoP\001Z=google.golang.org/genproto/goo" +
      "gleapis/gapic/metadata;metadata\252\002\025Google" +
      ".Gapic.Metadata\312\002\025Google\\Gapic\\Metadata\352" +
      "\002\027Google::Gapic::Metadatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_gapic_metadata_GapicMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_gapic_metadata_GapicMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_gapic_metadata_GapicMetadata_descriptor,
        new java.lang.String[] { "Schema", "Comment", "Language", "ProtoPackage", "LibraryPackage", "Services", });
    internal_static_google_gapic_metadata_GapicMetadata_ServicesEntry_descriptor =
      internal_static_google_gapic_metadata_GapicMetadata_descriptor.getNestedTypes().get(0);
    internal_static_google_gapic_metadata_GapicMetadata_ServicesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_gapic_metadata_GapicMetadata_ServicesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_descriptor =
      internal_static_google_gapic_metadata_GapicMetadata_descriptor.getNestedTypes().get(1);
    internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_descriptor,
        new java.lang.String[] { "Clients", "ApiVersion", });
    internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_ClientsEntry_descriptor =
      internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_descriptor.getNestedTypes().get(0);
    internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_ClientsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_gapic_metadata_GapicMetadata_ServiceForTransport_ClientsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_descriptor =
      internal_static_google_gapic_metadata_GapicMetadata_descriptor.getNestedTypes().get(2);
    internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_descriptor,
        new java.lang.String[] { "LibraryClient", "Rpcs", });
    internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_RpcsEntry_descriptor =
      internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_descriptor.getNestedTypes().get(0);
    internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_RpcsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_gapic_metadata_GapicMetadata_ServiceAsClient_RpcsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_gapic_metadata_GapicMetadata_MethodList_descriptor =
      internal_static_google_gapic_metadata_GapicMetadata_descriptor.getNestedTypes().get(3);
    internal_static_google_gapic_metadata_GapicMetadata_MethodList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_gapic_metadata_GapicMetadata_MethodList_descriptor,
        new java.lang.String[] { "Methods", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
