// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gapic/metadata/gapic_metadata.proto

package com.google.gapic.metadata;

public interface GapicMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.gapic.metadata.GapicMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Schema version of this proto. Current value: 1.0
   * </pre>
   *
   * <code>string schema = 1;</code>
   * @return The schema.
   */
  java.lang.String getSchema();
  /**
   * <pre>
   * Schema version of this proto. Current value: 1.0
   * </pre>
   *
   * <code>string schema = 1;</code>
   * @return The bytes for schema.
   */
  com.google.protobuf.ByteString
      getSchemaBytes();

  /**
   * <pre>
   * Any human-readable comments to be included in this file.
   * </pre>
   *
   * <code>string comment = 2;</code>
   * @return The comment.
   */
  java.lang.String getComment();
  /**
   * <pre>
   * Any human-readable comments to be included in this file.
   * </pre>
   *
   * <code>string comment = 2;</code>
   * @return The bytes for comment.
   */
  com.google.protobuf.ByteString
      getCommentBytes();

  /**
   * <pre>
   * Computer language of this generated language. This must be
   * spelled out as it spoken in English, with no capitalization or
   * separators (e.g. "csharp", "nodejs").
   * </pre>
   *
   * <code>string language = 3;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * Computer language of this generated language. This must be
   * spelled out as it spoken in English, with no capitalization or
   * separators (e.g. "csharp", "nodejs").
   * </pre>
   *
   * <code>string language = 3;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <pre>
   * The proto package containing the API definition for which this
   * GAPIC library was generated.
   * </pre>
   *
   * <code>string proto_package = 4;</code>
   * @return The protoPackage.
   */
  java.lang.String getProtoPackage();
  /**
   * <pre>
   * The proto package containing the API definition for which this
   * GAPIC library was generated.
   * </pre>
   *
   * <code>string proto_package = 4;</code>
   * @return The bytes for protoPackage.
   */
  com.google.protobuf.ByteString
      getProtoPackageBytes();

  /**
   * <pre>
   * The language-specific library package for this GAPIC library.
   * </pre>
   *
   * <code>string library_package = 5;</code>
   * @return The libraryPackage.
   */
  java.lang.String getLibraryPackage();
  /**
   * <pre>
   * The language-specific library package for this GAPIC library.
   * </pre>
   *
   * <code>string library_package = 5;</code>
   * @return The bytes for libraryPackage.
   */
  com.google.protobuf.ByteString
      getLibraryPackageBytes();

  /**
   * <pre>
   * A map from each proto-defined service to ServiceForTransports,
   * which allows listing information about transport-specific
   * implementations of the service.
   * The key is the name of the service as it appears in the .proto
   * file.
   * </pre>
   *
   * <code>map&lt;string, .google.gapic.metadata.GapicMetadata.ServiceForTransport&gt; services = 6;</code>
   */
  int getServicesCount();
  /**
   * <pre>
   * A map from each proto-defined service to ServiceForTransports,
   * which allows listing information about transport-specific
   * implementations of the service.
   * The key is the name of the service as it appears in the .proto
   * file.
   * </pre>
   *
   * <code>map&lt;string, .google.gapic.metadata.GapicMetadata.ServiceForTransport&gt; services = 6;</code>
   */
  boolean containsServices(
      java.lang.String key);
  /**
   * Use {@link #getServicesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.gapic.metadata.GapicMetadata.ServiceForTransport>
  getServices();
  /**
   * <pre>
   * A map from each proto-defined service to ServiceForTransports,
   * which allows listing information about transport-specific
   * implementations of the service.
   * The key is the name of the service as it appears in the .proto
   * file.
   * </pre>
   *
   * <code>map&lt;string, .google.gapic.metadata.GapicMetadata.ServiceForTransport&gt; services = 6;</code>
   */
  java.util.Map<java.lang.String, com.google.gapic.metadata.GapicMetadata.ServiceForTransport>
  getServicesMap();
  /**
   * <pre>
   * A map from each proto-defined service to ServiceForTransports,
   * which allows listing information about transport-specific
   * implementations of the service.
   * The key is the name of the service as it appears in the .proto
   * file.
   * </pre>
   *
   * <code>map&lt;string, .google.gapic.metadata.GapicMetadata.ServiceForTransport&gt; services = 6;</code>
   */
  /* nullable */
com.google.gapic.metadata.GapicMetadata.ServiceForTransport getServicesOrDefault(
      java.lang.String key,
      /* nullable */
com.google.gapic.metadata.GapicMetadata.ServiceForTransport defaultValue);
  /**
   * <pre>
   * A map from each proto-defined service to ServiceForTransports,
   * which allows listing information about transport-specific
   * implementations of the service.
   * The key is the name of the service as it appears in the .proto
   * file.
   * </pre>
   *
   * <code>map&lt;string, .google.gapic.metadata.GapicMetadata.ServiceForTransport&gt; services = 6;</code>
   */
  com.google.gapic.metadata.GapicMetadata.ServiceForTransport getServicesOrThrow(
      java.lang.String key);
}
